apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nhlbi-rdp-ingress
  namespace: nhlbi-prod
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-protocols: "TLSv1.2 TLSv1.3"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - rdp.nhlbi.nih.gov
      secretName: nhlbi-rdp-tls
  rules:
    - host: rdp.nhlbi.nih.gov
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nhlbi-rdp
                port:
                  number: 443
